travis-build: Install pyelftools locally
Travis builds are failing because elftools.elf.elffile module
is not being found.

ImportError: No module named elftools.elf.elffile

Not clear why this worked previously and started failing recently
but it can be resolved in one of two ways:

1) Add the global installation path to PYTHONPATH variable, or
2) Install pyelftools as local user

Option two is implemented here.

Signed-off-by: Jim Wylder <jwylder@motorola.com>