apps/builtin: better fix for building with parallel make
Build-server sometimes fails 'make -j24' with:

 In file included from builtin_list.c:62:0:
 builtin_list.h:1:46: error: 'ts_engine_main' undeclared here (not in a function)
  { "ts_engine", SCHED_PRIORITY_DEFAULT, 2048, ts_engine_main },

or sometimes silently succeeds but generates builds that contain
a random subset of configured NuttX applications. There are two
root causes for this:

1) Recipes for building builtin_list.h and builtin_proto.h are not
   linearizable.
2) Nothing ensures that 'make context' is run first for apps/builtin

This patch addresses both issues.

Change-Id: Ib2a4cd255bddb4b60f4f62cc47d1d4f2a715e741
Signed-off-by: Juha Niskanen <juha.niskanen@haltian.com>
Reviewed-on: http://gerrit.mot.com/780515
SME-Granted: SME Approvals Granted
Submit-Approved: Jira Key <jirakey@motorola.com>
Tested-by: Jira Key <jirakey@motorola.com>
SLTApproved: Slta Waiver <sltawvr@motorola.com>
Reviewed-by: James Wylder <jwylder@motorola.com>