mods: mhb_server: Make cdsi_from_inst static to fix build error
Some versions of gcc throw the following error when building:

  mhb_server.c:431:13: error: 'g_cdsi_blocks' is static but used in
  inline function 'cdsi_from_inst' which is not static [-Werror]

Signed-off-by: Greg Meiste <greg.meiste@gmail.com>